# Generated by Django 3.0.8 on 2020-07-20 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('data_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('trocos', models.CharField(choices=[('T1', 'Troço 1'), ('T2', 'Troço 2'), ('T3', 'Troço 3')], default='T1', max_length=2)),
                ('location', models.IntegerField(max_length=4, verbose_name='Pk')),
                ('tarefas', models.CharField(choices=[('TE', 'Terraplanagem'), ('DR', 'Drenagem'), ('PA', 'Pavimentação'), ('OB', 'Obras Acessórias'), ('SI', 'Sinalização e segurança'), ('OA', 'Obras de Arte'), ('DI', 'Diversos')], default='TE', max_length=2)),
                ('imagem_post', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem')),
            ],
        ),
    ]
