# Generated by Django 3.0.8 on 2020-07-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Pk'),
        ),
    ]
